// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChecker.Database;

namespace WebChecker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191112213732_websiteTable")]
    partial class websiteTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebChecker.Database.Entity.WebsiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartButtonXPatch");

                    b.Property<string>("MainUrl");

                    b.Property<string>("NameXPath");

                    b.Property<string>("PriceXPath");

                    b.HasKey("Id");

                    b.ToTable("WebsiteEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
